version: '3'
services: 
  edp-api-proxy:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: docker.52north.org/edp/edp-api-proxy:latest
    ports: 
      - 9090:9090
    environment: 
      - SEARCH_ENDPOINT=https://www.europeandataportal.eu/data/search/search
      - WHITELIST_UPDATE_INTERVAL_MINUTES=1
      - WHITELIST_STORAGE_DIR=/etc/ckan-whitelist.json
      - LOGGING_LEVEL=trace
    volumes:
      - /etc/ckan-whitelist.json:/etc/ckan-whitelist.json
