version: '3'
services: 
  new-pn:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: edp/mapapps-proxy
    ports: 
      - 9090:9090
    environment: 
      - EDP_DATA_API_URL=https://www.europeandataportal.eu/data
      - WHITELIST_UPDATE_INTERVAL_MINUTES=1
      - LOGGING_LEVEL=debug
    volumes:
      - /etc/ckan-whitelist.json:/etc/ckan-whitelist.json